<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- This project targets Windows. It is the only project that uses WASAPI and COM. -->
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdaVoice.Audio\AdaVoice.Audio.csproj" />
  </ItemGroup>

</Project>
