namespace AdaVoice.Server.Tests.Architecture;

// §14 pitfalls #16 (global filters don't cover writes/raw SQL) and #18 (string
// interpolation into raw SQL). Policy: no FromSqlRaw (use FromSqlInterpolated instead)
// and no deliberate query-filter bypass (IgnoreQueryFilters) outside a reviewed escape
// hatch. A reviewed escape hatch is marked with a `// tenant-scan-ok:` comment within the
// 6 physical lines immediately above the offending call — see
// AdaVoice.Server.Infrastructure/Persistence/Seeding/DatabaseSeeder.cs for the one
// legitimate example (the seeder runs under a null-tenant system provider and must see
// its own system-tenant rows).
//
// This guard does not police test code: tests legitimately call IgnoreQueryFilters to
// assert cross-tenant behavior (see TenantIsolationTests), so the whole
// AdaVoice.Server.Tests project is excluded from the scan.
public class RawSqlGuardTests
{
    private static readonly string[] ForbiddenSubstrings =
    {
        "FromSqlRaw(", ".IgnoreQueryFilters(", "ExecuteSqlRaw(", "ExecuteSqlRawAsync(", "SqlQueryRaw(",
    };
    private const string Marker = "tenant-scan-ok:";
    private const int MarkerWindowLines = 6;
    private const string ExcludedTestsProjectFolder = "AdaVoice.Server.Tests";

    [Fact]
    public void No_unreviewed_FromSqlRaw_or_IgnoreQueryFilters_in_server_code()
    {
        var offenders = ScanServerSources();

        Assert.True(
            offenders.Count == 0,
            "Forbidden raw-SQL / filter-bypass without a `// tenant-scan-ok:` marker:\n" +
            string.Join("\n", offenders));
    }

    private static List<string> ScanServerSources()
    {
        var serverDir = LocateServerDir();
        var offenders = new List<string>();

        foreach (var file in Directory.EnumerateFiles(serverDir, "*.cs", SearchOption.AllDirectories))
        {
            if (IsExcluded(file, serverDir))
            {
                continue;
            }

            var lines = File.ReadAllLines(file);

            if (IsGenerated(lines))
            {
                continue;
            }

            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i];

                foreach (var forbidden in ForbiddenSubstrings)
                {
                    if (!line.Contains(forbidden, StringComparison.Ordinal))
                    {
                        continue;
                    }

                    if (HasMarkerInWindow(lines, i))
                    {
                        continue;
                    }

                    offenders.Add($"{file}:{i + 1}: {line.Trim()}");
                }
            }
        }

        return offenders;
    }

    private static bool HasMarkerInWindow(string[] lines, int matchIndex)
    {
        // Strictly the lines *preceding* the match (matchIndex itself is excluded): the 6
        // physical lines above it, i.e. 0-indexed [matchIndex-6 .. matchIndex-1].
        var start = Math.Max(0, matchIndex - MarkerWindowLines);
        var end = matchIndex - 1;

        for (var i = start; i <= end; i++)
        {
            if (lines[i].Contains(Marker, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsGenerated(string[] lines)
    {
        // Standard tooling convention (EF Core's *.Designer.cs and *ModelSnapshot.cs among
        // others): a leading "<auto-generated" marker in the first couple of lines.
        for (var i = 0; i < Math.Min(2, lines.Length); i++)
        {
            if (lines[i].Contains("<auto-generated", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsExcluded(string file, string serverDir)
    {
        var relative = Path.GetRelativePath(serverDir, file);
        var segments = relative.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        foreach (var segment in segments)
        {
            if (string.Equals(segment, "obj", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(segment, "bin", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(segment, ExcludedTestsProjectFolder, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string LocateServerDir()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "AdaVoice.slnx")))
        {
            dir = dir.Parent;
        }

        if (dir is null)
        {
            throw new InvalidOperationException(
                $"Could not locate repo root (AdaVoice.slnx) from {AppContext.BaseDirectory}.");
        }

        return Path.Combine(dir.FullName, "server");
    }
}
